### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by ShivanshuPurohit** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#50]
When I run `pip install aspect_based_sentiment_analysis` it gets stuck indefinitely downloading boto3, after saying
```
INFO: pip is looking at multiple versions of boto3 to determine which version is compatible with other requirements. This could take a while.
```

**Comment by dnlbreen** [comment]
Not sure if this is the same problem, but I ran into this when trying to install the pip packages.

"If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
  ----------------------------------------
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot be installed directly"

The problem is with transformers <2.9.0, so simply install that version or later. If running in jupyter notebook, you'll also have to install ipywidgets.

**Comment by rolczynski** [comment]
It's now available the upgraded version 😊
